#!/bin/bash

alias ls="ls -G"
alias ll="ls -lh"
alias la="ls -lAh"

if echo | grep -q --color=tty ""; then
  alias grep="grep --color=tty"
fi

if [[ $(command -v nvim) ]]; then
  alias vim=nvim
fi

if [[ $(command -v xclip) ]]; then
  alias pbcopy="xclip -selection clipboard"
  alias pbpaste="xclip -selection clipboard -o"
fi

if [[ $(command -v xdg-open) ]]; then
  alias open="xdg-open"
fi
alias g="git"

alias pu="pushd"
alias po="popd"

alias view="vim -R"

# Might be run before autojump.sh is sourced,
# in which case `j` won't be a command yet.
if [[ $(command -v autojump) ]]; then
  alias z="j >/dev/null 2>&1"
fi

alias cats='(cd ~/workspace/cf-release/src/github.com/cloudfoundry/cf-acceptance-tests && CONFIG=$PWD/integration_config.json bin/test --nodes=3)'
# Deploying (bosh2 + cf-deployment)
alias upload_capi_release='~/workspace/capi-release/scripts/create-and-upload'
alias create_and_deploy='upload_capi_release && ~/workspace/capi-release/scripts/deploy'
alias create_and_force_deploy='upload_capi_release && ~/workspace/capi-release/scripts/deploy -n'
alias bootstrap_cf='~/workspace/capi-release/scripts/bootstrap-cf'
alias target_cf='~/workspace/capi-release/scripts/target-cf'
alias deploy='create_and_force_deploy'
alias print_env_info='pushd ~/workspace/capi-env-pool && git pull &&  ~/workspace/capi-ci/ci/bosh-lite/src/print_env_info && popd'
alias psql_bosh_lite='~/workspace/capi-release/scripts/psql-bosh-lite'
alias fixcommitter='~/workspace/perm-dotfiles/bin/fixcommitter'

# dev org/space setup
alias lite='(target_cf && cf rp test)'
alias relite='(target_cf && cf rp retest)'

# PSQL
alias psql_bosh_lite='~/workspace/capi-release/scripts/psql-bosh-lite'

