#!/bin/bash

# If not running interactively, don't do anything
case $- in
  *i*) ;;
  *) return;;
esac

# shellcheck source=/dev/null
[ -f ~/.fzf.bash ] && source ~/.fzf.bash

# shellcheck source=/dev/null
source ~/.shellrc
