#!/bin/bash

set -eu
set -o pipefail

function setup_perm_paths() {
  export PERM_RB_PATH="${HOME}/workspace/perm-rb"
  export PERM_GOPATH="${HOME}/workspace/perm-release"
  export PATH="${PATH}:${PERM_GOPATH}/bin"
}

function setup_perm_client_env() {
  export TEST_MYSQL_USERNAME="root"
  export TEST_MYSQL_PASSWORD="password"

  export PERM_TEST_SQL_DB_USERNAME="$TEST_MYSQL_USERNAME"
  export PERM_TEST_SQL_DB_PASSWORD="$TEST_MYSQL_PASSWORD"
}

function main() {
  setup_perm_paths
  setup_perm_client_env
}

main
