#!/bin/bash

export PATH="/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin:/bin:/sbin"

export GOPATH="${HOME}/.go"
GO_BIN_PATH="${GOPATH}/bin"
if [[ -r "${GO_BIN_PATH}" ]] && [[ -d "${GO_BIN_PATH}" ]]; then
  export PATH="${GO_BIN_PATH}:${PATH}"
fi

CARGO_BIN_PATH="${HOME}/.cargo/bin"
if [[ -r "${CARGO_BIN_PATH}" ]] && [[ -d "${CARGO_BIN_PATH}" ]]; then
  export PATH="${CARGO_BIN_PATH}:${PATH}"
fi

export DOCKER_BIN_PATH="${HOME}/.docker-bin"
if [[ -r "${DOCKER_BIN_PATH}" ]] && [[ -d "${DOCKER_BIN_PATH}" ]]; then
  export PATH="${DOCKER_BIN_PATH}:${PATH}"
fi

export CF_PLUGIN_HOME="${HOME}"
