#!/bin/bash

for file in ~/.{aliases,dockerfunc,exports,path}; do
  if [[ -r "${file}" ]] && [[ -f "${file}" ]]; then
    # shellcheck source=/dev/null
    source "${file}"
  fi
done

for file in ~/.functions/*; do
  if [[ -r "${file}" ]] && [[ -f "${file}" ]]; then
    # shellcheck source=/dev/null
    source "${file}"
  fi
done

# shellcheck source=/dev/null
[ -f /usr/local/etc/profile.d/autojump.sh ] && . /usr/local/etc/profile.d/autojump.sh

if command -v thefuck > /dev/null; then
  eval "$(thefuck --alias)"
fi
