#!/bin/env zsh

# Settings shared with bash
# shellcheck source=/dev/null
source ~/.shellrc

for file in ~/.zsh/*; do
  if [[ -r "${file}" ]] && [[ -f "${file}" ]]; then
		# shellcheck source=/dev/null
    source "${file}"
  fi
done

# From oh-my-zsh
# Save the location of the current completion dump file.
if [ -z "${ZSH_COMPDUMP}" ]; then
  ZSH_COMPDUMP="${ZDOTDIR:-${HOME}}/.zcompdump-${SHORT_HOST}-${ZSH_VERSION}"
fi

if [[ ${ZSH_DISABLE_COMPFIX} != 'true' ]]; then
  # If completion insecurities exist, warn the user without enabling completions.
  if ! compaudit &>/dev/null; then
    # This function resides in the "lib/compfix.zsh" script sourced above.
    handle_completion_insecurities
  # Else, enable and cache completions to the desired file.
  else
    compinit -d "${ZSH_COMPDUMP}"
  fi
else
  compinit -i -d "${ZSH_COMPDUMP}"
fi

if [[ -r ~/.fzf.zsh ]]; then
  # shellcheck source=/dev/null
  source ~/.fzf.zsh
fi

if [[ -f "/usr/local/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/path.zsh.inc" ]]; then
  source "/usr/local/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/path.zsh.inc"
fi
if [[ -f "/usr/local/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/completion.zsh.inc" ]]; then
  source "/usr/local/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/completion.zsh.inc"
fi

if command -v direnv > /dev/null; then
  eval "$(direnv hook zsh)"
fi

source /usr/local/opt/chruby/share/chruby/chruby.sh
source /usr/local/opt/chruby/share/chruby/auto.sh
